// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Andhika-GIT/Go-REST-Event-Management/app"
	"github.com/Andhika-GIT/Go-REST-Event-Management/controller"
	"github.com/Andhika-GIT/Go-REST-Event-Management/repository"
	"github.com/Andhika-GIT/Go-REST-Event-Management/service"
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"
)

// Injectors from injector.go:

func InitializedServer(option ...validator.Option) *chi.Mux {
	userRepository := repository.NewUserRepository()
	db := app.NewDB()
	validate := validator.New(option...)
	userService := service.NewUserService(userRepository, db, validate)
	userController := controller.NewUserController(userService)
	mux := app.NewRouter(userController)
	return mux
}
